openapi: 3.0.2

info:
  title: WhatsAppChatApi
  description: Описание API для сервиса WhatsAppChatApi
  version: 0.0.1

externalDocs:
  description: Ссылка на документацию GREEN API
  url: https://site.sw.slonbook.com/docs/
    
tags:
  - name: Account
    description: Методы работы с аккаунтом
  - name: Sending
    description: Методы отправки сообщений
  - name: Receiving
    description: Методы получения сообщений

paths:
  /getStateInstance:
    get:
      tags:
        - "Account"
      operationId: getStateInstance
      summary: Метод предназначен для получения состояния аккаунта.
      description: документация - https://green-api.com/docs/api/account/GetStateInstance/
      responses:
        200:
          $ref: "#/components/responses/getStateInstance"
        400:
          $ref: "#/components/responses/Error400"
        429:
          $ref: "#/components/responses/Error429"
        466:
          $ref: "#/components/responses/Error466"
        500:
          $ref: "#/components/responses/Error500"
  /getSettings:
    get:
      tags:
        - "Account"
      operationId: getSettings
      summary: The method is aimed for getting the current account settings.
      description: документация - https://green-api.com/en/docs/api/account/GetSettings/
      responses:
        200:
          $ref: "#/components/responses/getSettings"
        400:
          $ref: "#/components/responses/Error400"
        429:
          $ref: "#/components/responses/Error429"
        466:
          $ref: "#/components/responses/Error466"
        500:
          $ref: "#/components/responses/Error500"
  /sendMessage:
    post:
      tags:
        - "Sending"
      operationId: sendMessage
      summary: Отправить текстовое сообщение
      description: документация - https://green-api.com/docs/api/sending/SendMessage/
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sendMessageDto"
      responses:
        200:
          $ref: "#/components/responses/sendMessage"
        400:
          $ref: "#/components/responses/Error400"
        429:
          $ref: "#/components/responses/Error429"
        466:
          $ref: "#/components/responses/Error466"
        500:
          $ref: "#/components/responses/Error500"
  /receiveNotification:
    get:
      tags:
        - "Receiving"
      operationId: receiveNotification
      summary: Отправить текстовое сообщение
      description: документация - https://green-api.com/docs/api/receiving/technology-http-api/ReceiveNotification/
      responses:
        200:
          $ref: "#/components/responses/receiveNotification"
        400:
          $ref: "#/components/responses/Error400"
        429:
          $ref: "#/components/responses/Error429"
        466:
          $ref: "#/components/responses/Error466"
        500:
          $ref: "#/components/responses/Error500"
  /deleteNotification/{receiptId}:
    delete:
      tags:
        - "Receiving"
      operationId: deleteNotification
      summary: Удалить сообщение из очереди (отметить как прочитанное)
      description: документация - https://green-api.com/en/docs/api/receiving/technology-http-api/DeleteNotification/
      parameters:
        - $ref: "#/components/parameters/receiptId"
      responses:
        200:
          $ref: "#/components/responses/deleteNotification"
        400:
          $ref: "#/components/responses/Error400"
        429:
          $ref: "#/components/responses/Error429"
        466:
          $ref: "#/components/responses/Error466"
        500:
          $ref: "#/components/responses/Error500"

#  -------------------------------------------------------------------------------------------------------------------

components:
  parameters:
    receiptId:
      name: receiptId
      in: path
      description: Receipt Id for deleting an incoming notification received by ReceiveNotification method
      required: true
      schema:
        type: integer

  responses:
    getStateInstance:
      description: Ответ метода getStateInstance
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/getStateInstanceRes"
    getSettings:
      description: Ответ метода getSettings
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/getSettingsRes"
    sendMessage:
      description: Ответ метода sendMessage
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/sendMessageRes"
    receiveNotification:
      description: Ответ метода receiveNotification
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/receiveNotificationRes"
    deleteNotification:
      description: Ответ метода deleteNotification
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/deleteNotificationRes"

    Error400:
      description: bad request data
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"
    Error429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"
    Error466:
      description: correspondentsStatus
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"
    Error500:
      description: "File from url exceeded max upload size. Size: XXXXmb Limit: 100mb Url:"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"

  schemas:
    sendMessageDto:
      title: sendMessageDto
      type: object
      description: Тело запроса для метода sendMessage
      required:
        - "chatId"
        - "message"
      properties:
        chatId:
          type: string
          description: Идентификатор чата
        message:
          type: string
          description: Текст сообщения. Поддерживаются символы emoji 😃
        quotedMessageId:
          type: string
          description: Идентификатор цитируемого сообщения,если указан то сообщение отправится с цитированием указанного сообщения чата
        archiveChat:
          type: string
          description: "Помещает в архив чат, в который отправлено сообщение. Принимает значения: true"
        linkPreview:
          type: string
          description: "Параметр включает отображение превью и описание ссылки. По умолчанию включен. Принимает значения: true/false"
    getChatHistoryDto:
      title: getChatHistoryDto
      type: object
      required:
        - "chatId"
        - "count"
      properties:
        chatId:
          type: string
          description: Personal or chat Id the message history of which you need to get
        count:
          type: integer
          description: The number of messages to get. The default is 100
      example:
        chatId: "11001234567@c.us"
        count: 10

    getStateInstanceRes:
      title: getStateInstanceRes
      type: object
      required:
        - "stateInstance"
      properties:
        stateInstance:
          type: string
          enum:
            - "notAuthorized"
            - "authorized"
            - "blocked"
            - "sleepMode"
            - "starting"
          description: Состояние аккаунта
    getSettingsRes:
      title: getSettingsRes
      type: object
      required:
        - "wid"
      properties:
        wid:
          type: string
          description: Account ID in WhatsApp
        countryInstance:
          type: string
          description: Account country code in accordance with standard ISO 3166-2
        typeAccount:
          type: string
          description: "Account type, possible variants: trial, production, vip"
        webhookUrl:
          type: string
          description: URL to receive incoming notifications
        webhookUrlToken:
          type: string
          description: Token for connecting to your webhook server
        delaySendMessagesMilliseconds:
          type: integer
          description: Message sending delay is in milliseconds
        markIncomingMessagesReaded:
          type: string
          enum:
            - "yes"
            - "no"
          description: "Mark incoming messages as read or not, possible variants: yes, no. Ignored if markIncomingMessagesReadedOnReply is 'yes'."
        markIncomingMessagesReadedOnReply:
          type: string
          enum:
            - "yes"
            - "no"
          description: "Mark incoming messages as read when sending a message to the chat via API, possible variants: yes, no. If 'yes', then markIncomingMessagesReaded setting is ignored."
        outgoingWebhook:
          type: string
          enum:
            - "yes"
            - "no"
          description: "Get notifications about outgoing messages sending / delivering / reading status, possible variants: yes, no"
        outgoingMessageWebhook:
          type: string
          enum:
            - "yes"
            - "no"
          description: "Get notifications about messages sent from phone, possible variants: yes, no"
        stateWebhook:
          type: string
          enum:
            - "yes"
            - "no"
          description: "Get notifications about changes in the account authorization status, possible variants: yes, no"
        incomingWebhook:
          type: string
          enum:
            - "yes"
            - "no"
          description: "Get notifications about incoming messages and files, possible variants: yes, no"
        deviceWebhook:
          type: string
          enum:
            - "yes"
            - "no"
          description: "Get notifications about the device (phone) and battery level, possible variants: yes, no"
        statusInstanceWebhook:
          type: string
          enum:
            - "yes"
            - "no"
          description: "Get notifications about the account socket connection status change, possible variants: yes, no"
        sendFromUTC:
          type: string
          description: "Get the account setting - the delay of sending from the queue within the time interval AFTER the specified one (Attention, the time is indicated in UTC), possible variants: 09:00"
        sendToUTC:
          type: string
          description: "Get the account setting - the delay of sending from the queue within the time interval BEFORE the specified one (Attention, the time is indicated in UTC), possible variants: 12:00"
        sharedSession:
          type: string
          description: "Это поле не описано в документации, но по факту может прийти"
        proxyInstance:
          type: string
          description: "Это поле не описано в документации, но по факту может прийти"
        outgoingAPIMessageWebhook:
          type: string
          description: "Это поле не описано в документации, но по факту может прийти"
        enableMessagesHistory:
          type: string
          description: "Это поле не описано в документации, но по факту может прийти"
        keepOnlineStatus:
          type: string
          description: "Это поле не описано в документации, но по факту может прийти"
    sendMessageRes:
      title: sendMessageRes
      type: object
      required:
        - "idMessage"
      properties:
        idMessage:
          type: string
          description: Идентификатор отправленного сообщения
      example:
        idMessage: "1"
    receiveNotificationRes:
      title: receiveNotificationRes
      type: object
      required:
        - "receiptId"
        - "body"
      properties:
        receiptId:
          type: integer
          description: Идентификатор доставки для удаления входящего уведомления методом DeleteNotification
        body:
          type: object
          description: Входящее уведомление согласно Формату входящих уведомлений
          properties:
            typeWebhook:
              type: string
            sendByApi:
              type: boolean
            status:
              type: string
            instanceData:
              type: object
              required:
                - "idInstance"
                - "wid"
                - "typeInstance"
              properties:
                idInstance:
                  type: integer
                wid:
                  type: string
                typeInstance:
                  type: string
            timestamp:
              type: integer
            idMessage:
              type: string
            senderData:
              type: object
              required:
                - "chatId"
                - "sender"
                - "senderName"
                - "chatName"
              properties:
                chatId:
                  type: string
                sender:
                  type: string
                senderName:
                  type: string
                chatName:
                  type: string
            messageData:
              type: object
              required:
                - "typeMessage"
              properties:
                typeMessage:
                  type: string
                textMessageData:
                  type: object
                  required:
                    - "textMessage"
                  properties:
                    textMessage:
                      type: string
                fileMessageData:
                  type: object
                  properties:
                    caption:
                      type: string
                    downloadUrl:
                      type: string
                    fileName:
                      type: string
                    jpegThumbnail:
                      type: string
                    mimeType:
                      type: string
      example:
        receiptId: 1234567
        body:
          typeWebhook: "incomingMessageReceived"
          instanceData:
            idInstance: 1234,
            wid: "11001234567@c.us"
            typeInstance: "whatsapp"
          timestamp: 1588091580
          idMessage: "F7AEC1B7086ECDC7E6E45923F5EDB825"
          senderData:
            chatId: "79001234568@c.us"
            sender: "79001234568@c.us"
            senderName: "Green API"
          messageData:
            typeMessage: "textMessage"
            textMessageData:
              textMessage:"I use Green-API to send this message to you!"
    deleteNotificationRes:
      title: deleteNotification
      type: object
      required:
        - "result"
      properties:
        result:
          type: boolean
          description: "Incoming notification deleting result: true - incoming notification successfully deleted from the queue; false - notification is not deleted - possible, if the notification was deleted earlier or receiptId doesn't correspond to the value previously received by ReceiveNotification method"
      example:
        result: true

    ErrorModel:
      title: ErrorModel
      type: object
      required:
        - "number"
        - "timestamp"
        - "path"
        - "message"
      properties:
        statusCode:
          type: number
        timestamp:
          type: string
        path:
          type: string
        message:
          type: string
      example:
        statusCode: 400
        timestamp: "2023-05-14T09:19:01.738Z"
        path: "/waInstance1111111111/methods/xxx"
        message: "some error"
