openapi: 3.0.2

info:
  title: WhatsAppChatApi
  description: Описание API для сервиса WhatsAppChatApi
  version: 0.0.1

externalDocs:
  description: Ссылка на документацию GREEN API
  url: https://site.sw.slonbook.com/docs/
    
tags:
  - name: Account
    description: Методы работы с аккаунтом
  - name: Sending
    description: Методы отправки сообщений
  - name: Receiving
    description: Методы получения сообщений
  - name: Journals
    description: Методы истории сообщений

paths:
  /sendMessage:
    post:
      tags:
        - "Sending"
      operationId: sendMessage
      summary: Отправить текстовое сообщение
      description: документация - https://green-api.com/docs/api/sending/SendMessage/
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sendMessageDto"
      responses:
        200:
          $ref: "#/components/responses/sendMessage"
        400:
          $ref: "#/components/responses/Error400"
        429:
          $ref: "#/components/responses/Error429"
        466:
          $ref: "#/components/responses/Error466"
        500:
          $ref: "#/components/responses/Error500"
  /receiveNotification:
    get:
      tags:
        - "Receiving"
      operationId: receiveNotification
      summary: Отправить текстовое сообщение
      description: документация - https://green-api.com/docs/api/receiving/technology-http-api/ReceiveNotification/
      responses:
        200:
          $ref: "#/components/responses/receiveNotification"
        400:
          $ref: "#/components/responses/Error400"
        429:
          $ref: "#/components/responses/Error429"
        466:
          $ref: "#/components/responses/Error466"
        500:
          $ref: "#/components/responses/Error500"
  /getStateInstance:
    get:
      tags:
        - "Account"
      operationId: getStateInstance
      summary: Метод предназначен для получения состояния аккаунта.
      description: документация - https://green-api.com/docs/api/account/GetStateInstance/
      responses:
        200:
          $ref: "#/components/responses/getStateInstance"
        400:
          $ref: "#/components/responses/Error400"
        429:
          $ref: "#/components/responses/Error429"
        466:
          $ref: "#/components/responses/Error466"
        500:
          $ref: "#/components/responses/Error500"
  /deleteNotification/{receiptId}:
    delete:
      tags:
        - "Receiving"
      operationId: deleteNotification
      summary: Удалить сообщение из очереди (отметить как прочитанное)
      description: документация - https://green-api.com/en/docs/api/receiving/technology-http-api/DeleteNotification/
      parameters:
        - $ref: "#/components/parameters/receiptId"
      responses:
        200:
          $ref: "#/components/responses/deleteNotification"
        400:
          $ref: "#/components/responses/Error400"
        429:
          $ref: "#/components/responses/Error429"
        466:
          $ref: "#/components/responses/Error466"
        500:
          $ref: "#/components/responses/Error500"
  /getChatHistory:
    post:
      tags:
        - "Journals"
      operationId: getChatHistory
      summary: Получить историю чата
      description: документация - https://green-api.com/en/docs/api/journals/GetChatHistory/
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/getChatHistoryDto"
      responses:
        200:
          $ref: "#/components/responses/getChatHistory"
        400:
          $ref: "#/components/responses/Error400"
        429:
          $ref: "#/components/responses/Error429"
        466:
          $ref: "#/components/responses/Error466"
        500:
          $ref: "#/components/responses/Error500"

#  -------------------------------------------------------------------------------------------------------------------

components:
  parameters:
    receiptId:
      name: receiptId
      in: path
      description: Receipt Id for deleting an incoming notification received by ReceiveNotification method
      required: true
      schema:
        type: integer

  responses:
    getStateInstance:
      description: Ответ метода getStateInstance
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/getStateInstanceRes"
    sendMessage:
      description: Ответ метода sendMessage
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/sendMessageRes"
    receiveNotification:
      description: Ответ метода receiveNotification
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/receiveNotificationRes"
    deleteNotification:
      description: Ответ метода deleteNotification
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/deleteNotificationRes"
    getChatHistory:
      description: Ответ метода getChatHistory
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/getChatHistoryRes"

    Error400:
      description: bad request data
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"
    Error429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"
    Error466:
      description: correspondentsStatus
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"
    Error500:
      description: "File from url exceeded max upload size. Size: XXXXmb Limit: 100mb Url:"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"

  schemas:
    sendMessageDto:
      title: sendMessageDto
      type: object
      description: Тело запроса для метода sendMessage
      required:
        - "chatId"
        - "message"
      properties:
        chatId:
          type: string
          description: Идентификатор чата
        message:
          type: string
          description: Текст сообщения. Поддерживаются символы emoji 😃
        quotedMessageId:
          type: string
          description: Идентификатор цитируемого сообщения,если указан то сообщение отправится с цитированием указанного сообщения чата
        archiveChat:
          type: string
          description: "Помещает в архив чат, в который отправлено сообщение. Принимает значения: true"
        linkPreview:
          type: string
          description: "Параметр включает отображение превью и описание ссылки. По умолчанию включен. Принимает значения: true/false"
    getChatHistoryDto:
      title: getChatHistoryDto
      type: object
      required:
        - "chatId"
        - "count"
      properties:
        chatId:
          type: string
          description: Personal or chat Id the message history of which you need to get
        count:
          type: integer
          description: The number of messages to get. The default is 100
      example:
        chatId: "11001234567@c.us"
        count: 10

    getStateInstanceRes:
      title: getStateInstanceRes
      type: object
      required:
        - "stateInstance"
      properties:
        stateInstance:
          type: string
          enum:
            - "notAuthorized"
            - "authorized"
            - "blocked"
            - "sleepMode"
            - "starting"
          description: Состояние аккаунта
      example:
        stateInstance: "authorized"
    sendMessageRes:
      title: sendMessageRes
      type: object
      required:
        - "idMessage"
      properties:
        idMessage:
          type: string
          description: Идентификатор отправленного сообщения
      example:
        idMessage: "1"
    receiveNotificationRes:
      title: receiveNotificationRes
      type: object
      required:
        - "receiptId"
        - "body"
      properties:
        receiptId:
          type: integer
          description: Идентификатор доставки для удаления входящего уведомления методом DeleteNotification
        body:
          type: object
          description: Входящее уведомление согласно Формату входящих уведомлений
          required:
            - "typeWebhook"
            - "instanceData"
            - "timestamp"
            - "idMessage"
            - "senderData"
            - "messageData"
          properties:
            typeWebhook:
              type: string
            instanceData:
              type: object
              required:
                - "idInstance"
                - "wid"
                - "typeInstance"
              properties:
                idInstance:
                  type: integer
                wid:
                  type: string
                typeInstance:
                  type: string
            timestamp:
              type: integer
            idMessage:
              type: string
            senderData:
              type: object
              required:
                - "chatId"
                - "sender"
                - "senderName"
              properties:
                chatId:
                  type: string
                sender:
                  type: string
                senderName:
                  type: string
            messageData:
              type: object
              required:
                - "typeMessage"
                - "textMessageData"
              properties:
                typeMessage:
                  type: string
                textMessageData:
                  type: object
                  required:
                    - "textMessage"
                  properties:
                    textMessage:
                      type: string

      example:
        receiptId: 1234567
        body:
          typeWebhook: "incomingMessageReceived"
          instanceData:
            idInstance: 1234,
            wid: "11001234567@c.us"
            typeInstance: "whatsapp"
          timestamp: 1588091580
          idMessage: "F7AEC1B7086ECDC7E6E45923F5EDB825"
          senderData:
            chatId: "79001234568@c.us"
            sender: "79001234568@c.us"
            senderName: "Green API"
          messageData:
            typeMessage: "textMessage"
            textMessageData:
              textMessage:"I use Green-API to send this message to you!"
    deleteNotificationRes:
      title: deleteNotification
      type: object
      required:
        - "result"
      properties:
        result:
          type: boolean
          description: "Incoming notification deleting result: true - incoming notification successfully deleted from the queue; false - notification is not deleted - possible, if the notification was deleted earlier or receiptId doesn't correspond to the value previously received by ReceiveNotification method"
      example:
        result: true
    getChatHistoryRes:
      title: getChatHistoryRes
      type: array
      items:
        required:
          - "type"
          - "timestamp"
          - "idMessage"
          - "typeMessage"
          - "chatId"
          - "senderName"
          - "textMessage"
        properties:
          type:
            type: string
          timestamp:
            type: integer
          idMessage:
            type: string
          typeMessage:
            type: string
          chatId:
            type: string
          senderId:
            type: string
          senderName:
            type: string
          textMessage:
            type: string
        example:
          - type: "incoming"
            timestamp: 1603964449
            idMessage: "3AADDD555CB0822C0539"
            typeMessage: "textMessage"
            chatId: "11001234567@c.us"
            senderId: "11001234567@c.us"
            senderName: "Andrew Sh"
            textMessage: "I use Green-API to get this message from you!"
          - type: "outgoing"
            timestamp: 1603964445
            idMessage: "3EB08816FEBCCC3FACD2"
            statusMessage: "read"
            typeMessage: "textMessage"
            chatId: "11001234567@c.us"
            textMessage: "I use Green-API to send this message to you!"
          - type: "incoming"
            timestamp: 1603964444
            idMessage: "3AA45F9F285C5249CDFC"
            typeMessage: "imageMessage"
            chatId: "11001234567@c.us"
            senderId: "11001234567@c.us"
            senderName: "Andrew Sh"
            downloadUrl: http://api.green-api.com/waInstance9075/downloadFile/download-file-id"
            caption: "Green-API Logo"

    ErrorModel:
      title: ErrorModel
      type: object
      required:
        - "number"
        - "timestamp"
        - "path"
        - "message"
      properties:
        statusCode:
          type: number
        timestamp:
          type: string
        path:
          type: string
        message:
          type: string
      example:
        statusCode: 400
        timestamp: "2023-05-14T09:19:01.738Z"
        path: "/waInstance1111111111/methods/xxx"
        message: "some error"
